### ISSUE TITLE
How did you create the nms file?

### ISSUE THREAD

**Issue by srubenacker** [Hyuto/yolov8-onnxruntime-web#1]
nms-yolov8.onnx

**Comment by Hyuto** [comment]
Hello, I created those onnx file using [ONNX GraphSurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html). The file is generated using this script [nms-onnx-v8.py](https://github.com/Hyuto/fun/blob/master/test-onnx-graph-surgeon/nms-onnx-v8.py).

You can view the model graph via netron [here](https://netron.app/?url=https://raw.githubusercontent.com/Hyuto/yolov8-onnxruntime-web/master/public/model/nms-yolov8.onnx)

**Comment by srubenacker** [comment]
Thank you so much! This is a great project!

Does the NMS work with all of the model sizes, e.g. n, s, m, l, x?

**Comment by Hyuto** [comment]
> Thank you so much! This is a great project!
> 
> Does the NMS work with all of the model sizes, e.g. n, s, m, l, x?

Yes it is. 😀
