### ISSUE TITLE
I run the program and it keeps loading o(╥﹏╥)o

### ISSUE THREAD

**Issue by chenyu-T** [Hyuto/yolov8-onnxruntime-web#2]
![image](https://github.com/Hyuto/yolov8-onnxruntime-web/assets/74364953/b7280328-b80a-41d9-8eb3-436514c1aad8)

**Comment by Hyuto** [comment]
Hello, 

Did you run it on your PC or via https://hyuto.github.io/yolov8-onnxruntime-web/ ?
