### ISSUE TITLE
Question about nms model

### ISSUE THREAD

**Issue by ferotek** [Hyuto/yolov8-onnxruntime-web#7]
Hi, I was wondering how you created the custom NMS model? Thanks

**Comment by Hyuto** [comment]
Hello, I created custom nms model using library called [`onnx_graphsurgeon`](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html), with this code https://github.com/Hyuto/fun/blob/master/test-onnx-graph-surgeon/nms-onnx-v8.py

**Comment by Hyuto** [comment]
Since there is no further discussion. I'm clossing this issue
